[package]
name = "opengpt"
version = "0.1.0"
edition = "2021"
description = "OpenGPT - A command-line interface to ChatGPT\nGithub: https://github.com/gngpp/opengpt"
license = "MIT"
homepage = "https://github.com/gngpp/opengpt"
repository = "https://github.com/gngpp/opengpt.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
thiserror = "1.0"
log = "0.4.17"
env_logger = "0.10.0"
chrono = "0.4.22"
clap = { version = "4.3.0", features = ["derive", "env"] }
reqwest = { version = "0.11.18", default-features = false, features = ["socks"] }
tokio = { version = "1.23.1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.81"
serde = "1.0.163"
url = "2.3.1"
base64 = "0.21.2"
openai = { path = "openai" }

[profile.dev]
opt-level = 'z'

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = "abort"
strip = true