[package]
name = "opengpt"
version = "0.1.0"
edition = "2021"
description = "OpenGPT - A command-line interface to ChatGPT\nGithub: https://github.com/gngpp/opengpt"
license = "MIT"
homepage = "https://github.com/gngpp/opengpt"
repository = "https://github.com/gngpp/opengpt.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
thiserror = "1.0"
log = "0.4.18"
env_logger = "0.10.0"
chrono = "0.4.22"
clap = { version = "4.3.0", features = ["derive", "env"] }
reqwest = { version = "0.11", features = ["json", "stream", "rustls-tls"] }
tokio = { version = "1.23.1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.81"
serde = {version = "1.0", features = ["derive"] }
url = "2.3.1"
openai = { path = "openai" }
jsonwebtokens = "1.2.0"
bytes = "1.0"
futures-util = "0.3"
rustls = "0.21.1"
gohttp = { path = "gohttp" }
derive_builder = "0.12.0"

[build.dependencies]
bindgen = "0.65.1"

[[bin]]
name = "opengpt"
path = "src/main.rs"

[profile.dev]
opt-level = 'z'

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = "abort"
strip = true
