version: '3'
services:
  ninja:
    image: gngpp/ninja:0.9.13
    command: run
    ports:
     - '7999:7999'
    volumes:
      - ./models:/models      
      - ./har/gpt4:/root/.ninja/gpt4
    environment:
      - LOG=info
      - ARKOSE_SOLVER=Fcsrv
      - ARKOSE_SOLVER_ENDPOINT=http://fcsrv:8000/task
      - ENABLE_ARKOSE_PROXY=true
      - ARKOSE_GPT3_EXPERIMENT=true
      - ARKOSE_GPT3_EXPERIMENT_SOLVER=true
    container_name: ninja
    
  fcsrv:
    image: ghcr.io/gngpp/fcsrv:latest
    # ports:
    #   - '8000:8000'
    command: run 
    environment:
      - MODEL_DIR=/models
    volumes:
      - ./models/:/models
    container_name: fcsrv
  
  ninja-frontend:
    image: deeplythink/ninja:v0.0.1
    ports:
    - 3000:8000
    command: run
    volumes:
    - ./har/gpt4:/root/.ninja/gpt4
    environment:
    - "BIND=0.0.0.0:8000"
    - "NINJA_API_ENDPOINT=http://ninja:7999"
